services:
- type: web
  name: flask-audio-classifier
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  envVars:
  - key: FLASK_ENV
    value: production
  - key: CLOUDINARY_CLOUD_NAME
    value: hcvu40dvj
  - key: CLOUDINARY_API_KEY
    value: 523379171599888
  - key: CLOUDINARY_API_SECRET
    value: pD2VU84Ew_KMETn0o-6kdbjPFnU
  - key: TF_CPP_MIN_LOG_LEVEL
    value: '2'
  - key: TF_ENABLE_ONEDNN_OPTS
    value: '0'
  plan: free
